spring:
  kafka:
    bootstrap-servers: pop-os:9092
  cloud:
    config:
      enabled: false
    gateway:
      server:
        webmvc:
          routes:
            - id: authentication-service
              uri: http://authentication-service-srv:8080
              predicates:
                - Path=/api/v1/auth/**
            - id: accounts-service
              uri: http://accounts-service-srv:8081
              predicates:
                - Path=/api/v1/accounts/**
            - id: media-generation-service
              uri: http://media-generation-service-srv:8083
              predicates:
                - Path=/api/v1/media-generation/**
            - id: content-service
              uri: http://content-service-srv:8084
              predicates:
                - Path=/api/v1/content/**
application:
  security:
    jwt:
      algorithm: RS256
      public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5uD98RhaZcg9x9W8yXufSceb4hyRbuZg4pcCGfiag4ucnxZ8yglcQMPqUrdGm7q1tFPRhMomAtQhwSXlbH33zeL8Coe4qQ4mOCGS5ZsltY5rLapS41QYlsFLrQ6liw98ZFOBDorJcyMxdr1ABsmke3TUR2AyKIciJJ9BAhHwL6kIsQVln3DDltG+ZiEWWVCH9haFQ5ScutD2i+MK82gVpw0MKR+rdXLwKm3DF8Y0PuLM/EXesM5QuZ53IWT+S8NOlAvI3Ze9ZZp3RVEFYF6/nOAecQdr0tRIE4+pcRaPArMhEAUJWuGHL/jWEy/eXlNN5FS3HEmj2g9L3TtQCUtzWQIDAQAB